"""
Interview Agent Service (Stage 1: Base Structure & Mock Logic)
-------------------------------------------------------------
This module defines the InterviewAgent class, which encapsulates
all the AI/LLM interview logic.

In this first stage:
- It provides mock questions and simulated evaluations.
- It defines the exact input/output contracts so the rest of the application
  (API and frontend) is already built to handle real AI responses.

In future stages:
- You will replace the mock responses inside these methods with API calls
  to an LLM (such as Google Gemini, OpenAI, or local open-source models).
"""


class InterviewAgent:
    def __init__(self):
        # Initial mock question bank categorized by topic
        self.mock_questions = {
            "python": [
                "Can you explain the difference between a list and a tuple in Python?",
                "What is a Python decorator and when would you use one?",
                "How does memory management and garbage collection work in Python?",
            ],
            "ai_basics": [
                "What is the difference between supervised and unsupervised learning?",
                "Can you explain the bias-variance tradeoff in machine learning?",
                "What is an activation function in neural networks, and why is it needed?",
            ],
            "general": [
                "Tell me about a challenging technical project you built.",
                "How do you approach debugging an error you have never seen before?",
                "What strategies do you use to learn new technologies quickly?",
            ],
        }

    def start_interview(self, role="Software Engineer", topic="python"):
        """
        Starts a mock interview session and returns the initial question.

        Parameters:
            role (str): Target job role (e.g., 'Python Developer', 'AI Intern')
            topic (str): Category for questions ('python', 'ai_basics', 'general')

        Returns:
            dict: Session metadata and the first interview question
        """
        normalized_topic = topic.lower() if topic else "general"
        if normalized_topic not in self.mock_questions:
            normalized_topic = "general"

        first_question = self.mock_questions[normalized_topic][0]

        return {
            "session_id": "session-mock-001",
            "role": role,
            "topic": normalized_topic,
            "question_index": 1,
            "total_questions": len(self.mock_questions[normalized_topic]),
            "current_question": first_question,
            "status": "in_progress",
            "message": "Interview session started successfully.",
        }

    def evaluate_answer(self, question, answer):
        """
        Evaluates the candidate's answer and produces feedback.

        Parameters:
            question (str): The question asked by the agent
            answer (str): The candidate's response text

        Returns:
            dict: Evaluation results including score, feedback, strengths, and improvement suggestions
        """
        if not answer or not answer.strip():
            return {
                "score": 0,
                "feedback": "No answer was submitted. Please write a response to receive feedback.",
                "strengths": [],
                "improvements": [
                    "Please submit an answer before requesting an evaluation."
                ],
            }

        trimmed_answer = answer.strip()
        word_count = len(trimmed_answer.split())

        # Stage 1 placeholder evaluation simulating AI assessment
        # In Stage 2+, this will be generated by prompting an LLM.
        return {
            "question": question,
            "submitted_answer": trimmed_answer,
            "word_count": word_count,
            "score": 8,  # Mock score out of 10
            "feedback": (
                "Mock Feedback (Stage 1): Your answer was recorded successfully! "
                "In Stage 2, the Interview Agent will analyze your response for technical accuracy, "
                "depth of explanation, and communication clarity."
            ),
            "strengths": [
                "Clear and structured communication.",
                "Directly addressed the question prompt.",
            ],
            "improvements": [
                "Include a concrete code snippet or real-world example to strengthen the answer.",
                "Elaborate on edge cases or performance considerations.",
            ],
        }
